---
- name: Configure multitouch gestures
  when: desktop.x11_gestures
  tags: [gnome, gestures]
  vars:
    gesture_ext:
      - x11gestures@joseexposito.github.io
  block:
  - name: Install touchee and gnome-shell-extension-x11gestures
    kewlfft.aur.aur:
      use: paru
      name:
        - touchegg
        - touche
        - gnome-shell-extension-x11gestures
    become: yes
    become_user: aur_builder

  - name: Enable gnome-shell-extension-x11gestures extensions (available after restarting)
    dconf:
      key: "/org/gnome/shell/enabled-extensions"
      value: "{{ desktop.gnome.extensions + gesture_ext }}"
    become: yes
    become_user: '{{ system.username }}'
  
  - name: Enable touchegg
    shell: systemctl enable touchegg

  - name: debug
    debug:
      msg: "Installed extensions: {{ desktop.gnome.extensions + gesture_ext }}"
    when: debug
    become: yes
    become_user: '{{ system.username }}'
