---
- name: Configure multitouch gestures
  tags: [gnome, gestures]
  block:
  - name: Install touchee and gnome-shell-extension-x11gestures
    kewlfft.aur.aur:
      use: paru
      name:
        - touchegg
        - touche
        - gnome-shell-extension-x11gestures
    become: yes
    become_user: aur_builder
    when: enable_xorg_multitouch_gestures

  - name: Enable gnome-shell-extension-x11gestures extensions (available after restarting)
    dconf:
      key: "/org/gnome/shell/enabled-extensions"
      value: "{{ gnome_extensions + gnome_extensions_multitouch }}"

  - name: debug
    debug:
      msg: "Installed extensions: {{ gnome_extensions + gnome_extensions_multitouch }}"
    when: debug
