---
- name: Install gnome
  tags: gnome
  block:
    - name: Install gnome packages
      community.general.pacman:
        name:
          - gdm
          - gnome
          - gnome-connections
          - gnome-tweaks
          - gnome-usage
          - gnome-system-monitor
          - gnome-sound-recorder
          - dconf-editor
          - python-psutil
          - gnome-software-packagekit-plugin
          - networkmanager
          - networkmanager-openvpn
          - seahorse
        state: present
        update_cache: yes
    - name: Install gnome extensions
      community.general.pacman:
        name:
          - gnome-shell-extension-appindicator
        state: present
        update_cache: yes
    - name: Install gnome extensions from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - gnome-shell-extension-system-monitor-git
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-desktop-icons-ng
          - gnome-shell-extension-just-perfection-desktop-git
          - chrome-gnome-shell
          - gnome-shell-extension-vitals
      become: yes
      become_user: aur_builder
    - name: "Enable gdm"
      shell: systemctl enable gdm
    - name: "Enable NetworkManager"
      shell: systemctl enable NetworkManager
    - name: "Enable power-profiles-daemon"
      shell: systemctl enable power-profiles-daemon

- name: Configure gnome
  import_tasks: dconf.yml

- name: Configure dash-to-dock
  import_tasks: dash-to-dock.yml

- name: Configure just-perfection
  import_tasks: just-perfection.yml

- name: Install toggle-touchpad
  import_tasks: toggle-touchpad.yml

- name: Configure gnome keybindings
  import_tasks: keybindings.yml

- name: Configure multitouch gestures (x11)
  import_tasks: gestures.yml

- name: Install flameshot
  import_tasks: flameshot.yml
