---
# The toggle-touchpad keybinding is created in keybindings.yml
- name: Configure gnome toggle-touchpad script
  tags: [gnome, gnome-config, toggle-touchpad]
  block:
    - name: Detect laptop version
      shell: "dmidecode -s system-version"
      register: laptop_version
      changed_when: false
      failed_when: false

    - name: Copy x1_toggle_touchpad.sh to /usr/local/bin
      when: laptop_version.stdout.find("Z16 Gen 2") == -1
      copy:
        src: "x1_toggle_touchpad.sh"
        dest: /usr/local/bin/x1_toggle_touchpad.sh
        force: yes
        mode: u+rwx,g-wx,o-rwx
        owner: "{{ system.username }}"
      become: yes
      become_user: "root"

    - name: Copy z16_toggle_touchpad.sh to /usr/local/bin
      when: laptop_version.stdout.find("Z16 Gen 2") != -1
      copy:
        src: "z16_toggle_touchpad.sh"
        dest: /usr/local/bin/z16_toggle_touchpad.sh
        force: yes
        mode: u+rwx,g-wx,o-rwx
        owner: "{{ system.username }}"
      become: yes
      become_user: "root"
