---
- name: Install cloud native packages
  tags: [packages, dev, cloudnative]
  block:
    - name: Install cloud native packages
      community.general.pacman:
        name:
          - aws-cli-v2
          - github-cli
          - yq
          - jq
          - jless
          - kubectl
          - k9s
          - helm
          - kustomize
          - terraform
          
    - name: Install cloud native packages from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - crane
          - pack-cli-bin
          - google-cloud-cli
          - google-cloud-cli-gke-gcloud-auth-plugin
          - kind
          - kubectx
          - kubetail
          - rancher-k3d-bin
          - stern
          - tmate
          - act
          - cosign
          - grype-bin
          - syft
      become: yes
      become_user: aur_builder

    - name: Install cloud native security packages
      tags: [packages, security]
      kewlfft.aur.aur:
        use: paru
        name:
          - cosign
          - grype-bin
          - syft
          - trivy

- name: Install development packages
  tags: [packages, dev]
  block:
    - name: Install development packages
      community.general.pacman:
        name:
          - nodejs-lts-gallium
          - npm
          - python-pipx
          - yarn
          - php
          - go
