---
- name: Install cloud native packages
  tags: [packages, dev, cloudnative]
  block:
    - name: Install cloud native packages
      community.general.pacman:
        name:
          - aws-cli-v2
          - github-cli
          - yq
          - jq
          - kubectl
          - k9s
          - helm
          - kustomize
          - terraform
    - name: Install cloud native packages from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - pack-cli-bin
          - google-cloud-sdk
          - google-cloud-sdk-gke-gcloud-auth-plugin
          - kind
          - kubectx
          - kubetail
          - rancher-k3d-bin
          - stern
          - tmate
          - act
          - flux-bin
      become: yes
      become_user: aur_builder

- name: Install development packages
  tags: [packages, dev]
  block:
    - name: Install development packages
      community.general.pacman:
        name:
          - nodejs-lts-gallium
          - npm
          - yarn
          - php
          - go
