---
- name: Productivity
  tags: [packages, productivity]
  block:
    - name: Install productivity packages
      community.general.pacman:
        name:
          - thefuck
          - yadm
          - gnupg
          - pinentry
          - telegram-desktop

    - name: Install productivity packages from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - slack-desktop
          - timeshift
          - visual-studio-code-bin
          - icu69-bin
          - zoom
          - xournalpp
      become: yes
      become_user: aur_builder
