---
- name: "Detect fingerprint reader"
  tags: [system, thinkpad]
  shell: 'lsusb | grep -i "fingerprint"'
  ignore_errors: yes
  register: is_fingerprint_reader

- name: Detect ThinkPad Z16 Gen2 fingerprint reader
  tags: [system, thinkpad]
  shell: 'lsusb  | grep "06cb:0123"'
  ignore_errors: yes
  register: is_fingerprint_reader_z16

- name: "Detect if device has a lid"
  tags: [system, thinkpad]
  shell: "cat /proc/acpi/button/lid/LID/state"
  ignore_errors: yes
  register: has_lid

- name: Better lid configuration
  tags: [system, thinkpad]
  when: has_lid.stdout != ""
  block:
    - name: Suspend on lid closing
      lineinfile:
        dest: /etc/systemd/logind.conf
        regexp: "^HandleLidSwitch="
        line: "HandleLidSwitch=suspend"
        mode: 0644
        backup: yes
    - name: Do nothing on lid closing with external power
      lineinfile:
        dest: /etc/systemd/logind.conf
        regexp: "^HandleLidSwitchExternalPower="
        line: "HandleLidSwitchExternalPower=ignore"
        mode: 0644
        backup: yes
    - name: Do nothing on lid closing when docked
      lineinfile:
        dest: /etc/systemd/logind.conf
        regexp: "^HandleLidSwitchDocked="
        line: "HandleLidSwitchDocked=ignore"
        mode: 0644
        backup: yes

- name: Install fingerprint reader (if hw is available)
  tags: [system, fingerprint]
  when: is_fingerprint_reader.rc == 0 or is_fingerprint_reader_z16.rc == 0
  block:
    - name: Install fprintd
      community.general.pacman:
        name:
          - fprintd
    - name: Add user to input group
      user:
        name: "{{ system.username }}"
        groups: input
        append: yes
